//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RageMP_VSupport.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RageMP_VSupport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;CDataFileMgr__ContentsOfDataFileXml&gt;
        ///	&lt;disabledFiles /&gt;
        ///	&lt;includedXmlFiles /&gt;
        ///	&lt;includedDataFiles /&gt;
        ///	&lt;dataFiles&gt;
        ///		&lt;!--vehicles&lt;Item&gt;
        ///			&lt;filename&gt;dlc_template:/data/vehicles.meta&lt;/filename&gt;
        ///			&lt;fileType&gt;VEHICLE_METADATA_FILE&lt;/fileType&gt;
        ///			&lt;overlay value=&quot;false&quot; /&gt;
        ///			&lt;disabled value=&quot;true&quot; /&gt;
        ///			&lt;persistent value=&quot;false&quot; /&gt;
        ///		&lt;/Item&gt;vehicles--&gt;
        ///		&lt;!--carcols&lt;Item&gt;
        ///			&lt;filename&gt;dlc_template:/data/carcols.meta&lt;/filename&gt;
        ///			&lt;fileType&gt;CARCOLS_FILE&lt;/fileT [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;SSetupData&gt;
        ///	&lt;deviceName&gt;dlc_template&lt;/deviceName&gt;
        ///	&lt;datFile&gt;content.xml&lt;/datFile&gt;
        ///	&lt;timeStamp&gt;00/00/0000 00:00:00&lt;/timeStamp&gt;
        ///	&lt;nameHash&gt;template&lt;/nameHash&gt;
        ///	&lt;contentChangeSetGroups&gt;
        ///		&lt;Item&gt;
        ///			&lt;NameHash&gt;GROUP_STARTUP&lt;/NameHash&gt;
        ///			&lt;ContentChangeSets&gt;
        ///				&lt;Item&gt;TEMPLATE_AUTOGEN&lt;/Item&gt;
        ///			&lt;/ContentChangeSets&gt;
        ///		&lt;/Item&gt;
        ///	&lt;/contentChangeSetGroups&gt;
        ///	&lt;type&gt;EXTRACONTENT_COMPAT_PACK&lt;/type&gt;
        ///	&lt;order value=&quot;9&quot; /&gt;
        ///&lt;/SSetupData&gt; ähnelt.
        /// </summary>
        internal static string setup2 {
            get {
                return ResourceManager.GetString("setup2", resourceCulture);
            }
        }
    }
}
